# Change these first
owner: xiotzsupport # Your GitHub organization or username, where this repository lives
repo: xIoTzcs-Uptime # The name of this repository

sites:

##Dovetail

  - name: 10_Dovetail
    url: https://www.dovetailindia.com/
  
  - name: 11_Dovetail
    url: https://clientonboarding.dovetailindia.com

  - name: 12_Dovetail
    url: https://dcms.dovetailindia.com

  - name: 13_Dovetail
    url: https://demo-clientonboarding.dovetailindia.com


# Vignesh to Revist - DR downtime 
#  - name: 14_Dovetail
#    url: https://eprotector.dovetailindia.com

# Vignesh to Revist - IP Whitelist
#  - name: 15_Dovetail
#    url: https://nav.dovetailindia.com/

  - name: 16_Dovetail
    url: http://navdev.dovetailindia.com

  - name: 17_Dovetail (https://oms.dovetailindia.com/)
    url: https://oms.dovetailindia.com/

  - name: 18_Dovetail
    url: https://oms-api.dovetailindia.com
  
  - name: 19_Dovetail
    url: https://api.uat.nav.dovetailindia.com/

##OneXtel
  - name: 21_OneXtel
    url:  https://vaptvoice.onextel.com
  
  - name: 22_OneXtel
    url: https://signature.onextel.com
  
  - name: 23_OneXtel
    url: https://service.onextel.com/
  
  - name: 24_OneXtel
    url: https://app.cpaas.onextel.com
  
  - name: 25_OneXtel
    url: https://assist.onextel.com
  
  - name: 26_OneXtel
    url: https://ats.onextel.com
  
  - name: 27_OneXtel
    url: https://blog.onextel.com/
  
  - name: 28_OneXtel
    url:  https://books.onextel.com
  
  - name: 29_OneXtel
    url: https://careers.onextel.com
  
  - name: 30_OneXtel
    url: https://celebrate.onextel.com/
  
  - name: 31_OneXtel
    url: https://chat.onextel.com
  
  - name: 32_OneXtel
    url: https://crm.onextel.com/
  
  - name: 33_OneXtel
    url: https://docs.onextel.com/
  
  - name: 34_OneXtel
    url: https://email.onextel.com/
  
  - name: 35_OneXtel
    url: https://global.onextel.com/


  ## Cornell
  - name: 41_Cornell
    url:  https://www.cornells.com.au/

  - name: 42_Cornell
    url:  https://webdisk.cornells.com.au/

  - name: 43_Cornell
    url:  https://cpanel.cornells.com.au/

  - name: 44_Cornell
    url:  https://webmail.cornells.com.au/


## Jesons
  - name: 91_Jesons
    url: https://autodiscover.jesons.net

  - name: 92_Jesons
    url: https://autodiscover.jesons.net

  - name: 93_Jesons
    url: https://www.jesons.net

  - name: 94_Jesons
    url: https://uat.jesons.net

  - name: 95_Jesons
    url: https://enterpriseenrollment.jesons.net


## JLMorison

  - name: 121_JLMorison
    url:  https://www.jlmorison.com

##Unishield360
  - name: 141_Unishield360
    url:  https://www.unishield360.com

  - name: 142_Unishield360
    url:  https://www.urbanplan.unishield360.com

##Medseven
  - name: 71_Medseven
    url: https://www.med7healthcare.com

  - name: 72_Medseven
    url: https://new.med7healthcare.com

  - name: 73_Medseven
    url: https://enterpriseenrollment.med7healthcare.com

  - name: 74_Medseven
    url: https://autodiscover.med7healthcare.com


##AlphaSeven
  - name: 151_AlphaSeven
    url: https://www.cicon.net

  - name: 152_AlphaSeven
    url: https://vpn.cicon.net

  - name: 153_AlphaSeven
    url: https://smtp.cicon.net

  - name: 154_AlphaSeven
    url: https://e.cicon.net

  - name: 155_AlphaSeven
    url: https://imap.cicon.net

  - name: 156_AlphaSeven
    url: https://mail.cicon.net


## AlOmeria
  - name: 171_ALOmeria
    url: https://www.omeirapp.ae


## Cicon
  - name: 181_Cicon
    url: https://www.cicon.net

  - name: 182_Cicon
    url: https://vpn.cicon.net

  - name: 183_Cicon
    url: https://smtp.cicon.net

  - name: 184_Cicon
    url: https://e.cicon.net

  - name: 185_Cicon
    url: https://imap.cicon.net

  - name: 185_Cicon
    url: https://mail.cicon.net
    
##Bell
  - name: 191_Bell
    url: https://bell-energy.com

##Gemini
  - name: 201_Gemini
    url: https://www.gti-me.com

  - name: 202_Gemini
    url: https://mail.gti-me.com

  - name: 203_Gemini
    url: https://cpanel.gti-me.com

  - name: 204_Gemini
    url: https://server.gti-me.com

  - name: 205_Gemini
    url: https://webdisk.gti-me.com

  - name: 206_Gemini
    url: https://webmail.gti-me.com

  - name: 207_Gemini
    url: https://xtrabakup.gti-me.com

  - name: 208_Gemini
    url: https://cpcontacts.gti-me.com









status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: Status-CX.xiotz.com
  #baseUrl: /xIoTzcs-Uptime

  logoUrl: https://raw.githubusercontent.com/xiotzsupport/xIoTz-Uptime/refs/heads/master/upptime-icon.svg
  name: xIoTz Customer Monitor
  introTitle: "xIoTz Uptime Monitoring - Customer."
  introMessage: xIoTz Websites Uptime - for Customers monitoring
  

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
